# THIS DOCKER COMPOSE IS USED TO LOCALLY TEST THE LIBRARY
services:

# Test Python compilation
  python-build:
    build: .
    volumes:
      - ../..:/repo
    working_dir: /repo/misc/python
    command: python3 -m build

  # Interactive shell for debugging
  shell:
    build: .
    volumes:
      - ../..:/repo
    working_dir: /repo/misc/python
    command: /bin/bash
    stdin_open: true
    tty: true
